### ISSUE TITLE
Only python 3.10 builds available

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/python-wasmer-split-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It looks like only builds compatible with 3.10 are available.

https://anaconda.org/conda-forge/python-wasmer/files

It would be lovely if #1 could be updated in such a way as to trigger building for a sane set of other pythons (e.g. >=3.7)

### Installed packages

```shell
python <3.10
```

### Environment info

```shell
-
```

**Comment by bollwyvl** [comment]
Hooray merge! But, hm, still seeing solvability [issues on a fastdiff build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=514937&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=95), the next onion layer of the graphene issue:

```
Mamba failed to solve:
 - pytest-cov
 - pytest <4
 - pytest-benchmark
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 226, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - pytest-cov
 - pytest <4
 - pytest-benchmark
 - python-wasmer-compiler-cranelift >=1.0.0
 - python >=3.6
 - python-wasmer >=1.0.0

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package python-wasmer-compiler-cranelift-1.1.0-h4b87306_0 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
- 

```

**Comment by wolfv** [comment]
What happens if you try to install these three locally?

```
 - python-wasmer-compiler-cranelift >=1.0.0
 - python >=3.6
 - python-wasmer >=1.0.0
```

**Comment by wolfv** [comment]
I just checked `CONDA_SUBDIR=linux-64 micromamba search python-wasmer-compiler-cranelift` and it _looks_ fine.

**Comment by bollwyvl** [comment]
yeah, and `--dry-run` works...

**Comment by bollwyvl** [comment]
i wonder if ` python-wasmer-compiler-*` should list `python` in `run`?
